# rigup configuration
# Define your AI agent rigs here

[rigs.default.riglets]
# Include riglets from this repository, including some derived from Anthropic's Skills
self = ["my-first-riglet", "algorithmic-art", "frontend-design"]
# Include riglets from external inputs
rigup = ["agent-rig-system", "riglet-creator", "nix-module-system"]

# Configuration for the riglets (if they define options)
[rigs.default.config]
# Override a riglet's disclosure in this rig
riglets.algorithmic-art.meta.disclosure = "shallow-toc"

# Local overrides:
# Create rigup.local.toml and add it to .gitignore to override config without modifying this file.
#
# rigup.local.toml can define new rigs that extend the ones defined here.
# 
# rigup CLI tool will automatically `git add` it so it is always part of the evaluated flake, even if gitignored.
